
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * `open_window` — create-if-needed, then show + focus the labelled window.
 *
 * For the picker the renderer passes the trigger's viewport rect
 * (`anchor_x`/`anchor_y`/`anchor_w`/`anchor_h`); we convert it to a screen
 * anchor via the CALLING window and place the popup. For the plain windows
 * the rect is absent and we center + show.
 */
async openWindow(label: string, anchorX: number | null, anchorY: number | null, anchorW: number | null, anchorH: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_window", { label, anchorX, anchorY, anchorW, anchorH }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `close_window` — HIDE the labelled keep-alive window so re-open keeps its
 * renderer state.
 */
async closeWindow(label: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `close_self_window` — hide the CALLING window (resolved from its own webview
 * label). Self-closing windows route their close button here instead of a bare
 * webview hide so each label's real teardown runs — above all the APP window,
 * whose close is a hide-to-tray or an app quit depending on the user's
 * `general.minimizeToTray` setting.
 */
async closeSelfWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_self_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
async pickerAnchorSnapshot() : Promise<PickerLifecycleSnapshot> {
    return await TAURI_INVOKE("picker_anchor_snapshot");
},
/**
 * Begin the one-time compositor warmup after the picker renderer mounts.
 * The renderer waits for real animation-frame callbacks before acknowledging
 * completion, replacing the old arbitrary 800 ms sleep.
 */
async pickerCompositorWarmupStart() : Promise<number | null> {
    return await TAURI_INVOKE("picker_compositor_warmup_start");
},
/**
 * Renderer acknowledgement that the off-screen picker has received actual
 * animation frames. A real open increments [`PICKER_SEQ`] and therefore owns
 * the window; a late warmup completion cannot hide it.
 */
async pickerCompositorWarmupComplete(sequence: number) : Promise<void> {
    await TAURI_INVOKE("picker_compositor_warmup_complete", { sequence });
},
/**
 * Renderer acknowledgement that the dropdown's real CSS exit completed.
 * A new open clears `closing`, so a late callback cannot hide its window.
 */
async pickerHideComplete() : Promise<void> {
    await TAURI_INVOKE("picker_hide_complete");
},
/**
 * `show_app_window` — surface + focus the app's one top-level window (the
 * settings window). The tray, second-instance launches, and the renderer's
 * startup reveal all funnel here.
 */
async showAppWindow() : Promise<void> {
    await TAURI_INVOKE("show_app_window");
},
/**
 * `hide_app_window` — dismiss the app window to the tray WITHOUT consulting
 * `general.minimizeToTray`.
 *
 * Distinct from `close_self_window` on purpose. Closing is a decision ("am I
 * done with this app?") and may quit; the Escape key is a dismissal ("get this
 * off my screen") and must never take the app down with it — Escape quitting
 * DimRead would also drop the user's display filters.
 */
async hideAppWindow() : Promise<void> {
    await TAURI_INVOKE("hide_app_window");
},
/**
 * `app_quit` — exit the app. The tray flyout's Quit row is the only caller
 * (the native tray menu it replaced owned this action).
 */
async appQuit() : Promise<void> {
    await TAURI_INVOKE("app_quit");
},
/**
 * `tray_menu_hide` — dismiss the popup (an item was activated, or Escape).
 */
async trayMenuHide() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_menu_hide") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `tray_menu_resize` — size the OS window to the renderer's measured content
 * (its `ResizeObserver` reports every change) and re-clamp against the tray
 * anchor so growth never pushes the popup under the taskbar.
 *
 * The no-op guard matters: `ResizeObserver` fires on every reflow (hover, a
 * focus ring, subpixel rounding), and an unguarded `set_size` would loop
 * resize → `Resized` → re-anchor → jitter.
 */
async trayMenuResize(width: number, height: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("tray_menu_resize", { width, height }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * Read the current settings tree with its revision.
 */
async settingsLoadSnapshot() : Promise<SettingsSnapshot> {
    return await TAURI_INVOKE("settings_load_snapshot");
},
/**
 * Apply a section-granular patch on top of revision `revision`.
 *
 * Errors with a "settings revision conflict" message when `revision` is no
 * longer current; succeeds with the NEW snapshot otherwise. Runtime
 * side-effects (autostart registration) and the `settings:changed` broadcast
 * run AFTER the write lock is released.
 */
async settingsSave(patch: PartialSettings, revision: number) : Promise<Result<SettingsSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("settings_save", { patch, revision }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * Start (or restart) a download. `id` is the caller-chosen registry key; the
 * file lands in the app-data downloads dir as `file_name` (a bare file name,
 * no path separators).
 */
async downloadStart(id: string, url: string, fileName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_start", { id, url, fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
async downloadPause(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_pause", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
async downloadResume(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_resume", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
async downloadCancel(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_cancel", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * Delete the downloaded file (and any partial) and drop the registry entry.
 */
async downloadRemove(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_remove", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
async downloadList() : Promise<DownloadSnapshot[]> {
    return await TAURI_INVOKE("download_list");
},
/**
 * Reveal the downloads directory in the OS file manager.
 */
async openDownloadsDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_downloads_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `hotkey_register` — validate + register `accelerator` under `id` (replacing
 * the id's previous accelerator). Errors with a typed message on an invalid
 * combo or one already owned by another id.
 */
async hotkeyRegister(id: string, accelerator: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_register", { id, accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `hotkey_unregister` — disarm the binding for `id` (idempotent).
 */
async hotkeyUnregister(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("hotkey_unregister", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `hotkey_list` — every live registration (id + accelerator), sorted by id.
 */
async hotkeyList() : Promise<HotkeyInfo[]> {
    return await TAURI_INVOKE("hotkey_list");
},
/**
 * `overlay_notify` — show the overlay pill with the given notification.
 */
async overlayNotify(payload: OverlayNotifyPayload) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("overlay_notify", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `overlay_dismiss` — dismiss the pill early (renderer exit + delayed hide).
 */
async overlayDismiss() : Promise<void> {
    await TAURI_INVOKE("overlay_dismiss");
},
/**
 * Latest notification for a race-free subscribe-then-snapshot handshake.
 */
async overlaySnapshot() : Promise<OverlaySnapshot> {
    return await TAURI_INVOKE("overlay_snapshot");
},
/**
 * Renderer acknowledgement that the CSS exit really completed. A newer
 * notification keeps the native window alive, making late callbacks harmless.
 */
async overlayHideComplete(sequence: number) : Promise<void> {
    await TAURI_INVOKE("overlay_hide_complete", { sequence });
},
/**
 * `display_list_monitors` — every physical monitor the engine can drive.
 */
async displayListMonitors() : Promise<MonitorInfo[]> {
    return await TAURI_INVOKE("display_list_monitors");
},
/**
 * `display_current` — the last applied output (Kelvin / brightness% / mode /
 * phase) for the real-time readout.
 */
async displayCurrent() : Promise<DisplayOutput> {
    return await TAURI_INVOKE("display_current");
},
/**
 * `display_preview` — live slider-drag on one monitor (or all when
 * `monitor_id` is `None`) without persisting. `endpoint_phase` makes supplied
 * values follow the same schedule interpolation as their eventual commit;
 * `None` requests a raw off-phase preview. A `None` axis keeps that axis at
 * each monitor's currently applied value.
 */
async displayPreview(kelvin: number | null, brightness: number | null, monitorId: string | null, endpointPhase: DisplayPhase | null) : Promise<void> {
    await TAURI_INVOKE("display_preview", { kelvin, brightness, monitorId, endpointPhase });
},
/**
 * `display_preview_end` — end the live preview and revert to the settings
 * output.
 */
async displayPreviewEnd() : Promise<void> {
    await TAURI_INVOKE("display_preview_end");
},
/**
 * `display_set_value` — persist ONE colour-temperature/brightness edit.
 *
 * The renderer sends the edit it wants, not a copy of the settings tree; the
 * read-modify-write happens in [`super::values::commit_edit`] under the
 * settings write lock. Every surface (Display tab, tray flyout, hotkeys) goes
 * through here, so they cannot drift apart or overwrite one another.
 *
 * Returns the post-write snapshot so the releasing surface can adopt the
 * committed value in the SAME turn it drops its local drag override. Waiting
 * for the `settings:changed` broadcast instead leaves the slider rendering the
 * pre-drag value for a frame — the visible snap-back on release. This matters
 * most in `pause`, where [`super::values::apply_edit_to`] also redirects the
 * edit into `custom` and moves `display.mode`, so the renderer's copy is wrong
 * about the mode as well as the value.
 */
async displaySetValue(edit: DisplayEdit) : Promise<Result<SettingsSnapshot, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("display_set_value", { edit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return __commandError__(e);
}
},
/**
 * `rules_list_windows` — enumerate candidate top-level windows for the rule
 * editor's picker, each with a stable `id` (its `HWND`) so same-process windows
 * stay distinguishable. Empty off-Windows.
 */
async rulesListWindows() : Promise<OpenWindow[]> {
    return await TAURI_INVOKE("rules_list_windows");
},
/**
 * `focus_read_toggle` — flip Focus Read; returns the new active state.
 */
async focusReadToggle() : Promise<boolean> {
    return await TAURI_INVOKE("focus_read_toggle");
},
/**
 * `focus_blur_toggle` — flip Focus Blur; returns the new active state.
 */
async focusBlurToggle() : Promise<boolean> {
    return await TAURI_INVOKE("focus_blur_toggle");
},
/**
 * `focus_active_state` — the current `{ read, blur }` activation.
 */
async focusActiveState() : Promise<FocusState> {
    return await TAURI_INVOKE("focus_active_state");
},
/**
 * Snapshot the latest cached Blur anchor. Renderers call this only after their
 * `focus:anchor` listener is installed (subscribe-then-snapshot handshake).
 */
async focusBlurAnchorSnapshot() : Promise<FocusAnchorEvent | null> {
    return await TAURI_INVOKE("focus_blur_anchor_snapshot");
},
/**
 * `magicx_toggle_effect` — toggle a per-window effect (`"dark"` | `"gray"`) on
 * the current Magic Toolbar target, falling back to the foreground window.
 */
async magicxToggleEffect(effect: string) : Promise<void> {
    await TAURI_INVOKE("magicx_toggle_effect", { effect });
},
/**
 * `magicx_clear_target` — clear all effects on the current toolbar target (the
 * toolbar's "Close" button; F9.2).
 */
async magicxClearTarget() : Promise<void> {
    await TAURI_INVOKE("magicx_clear_target");
},
/**
 * Renderer subscribe handshake: re-emit the current shown state only after the
 * webview confirms both toolbar listeners are registered.
 */
async magictoolbarRendererReady() : Promise<void> {
    await TAURI_INVOKE("magictoolbar_renderer_ready");
},
/**
 * Renderer exit-animation callback. The target guard makes a late completion
 * harmless if the toolbar was shown again before the old exit finished.
 */
async magictoolbarHideComplete() : Promise<void> {
    await TAURI_INVOKE("magictoolbar_hide_complete");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
autodarkChanged: AutoDarkChangedEvent,
displayState: DisplayStateEvent,
displayTopology: DisplayTopologyEvent,
downloadUpdate: DownloadUpdateEvent,
focusAnchor: FocusAnchorEvent,
focusCursor: FocusCursorEvent,
focusState: FocusStateEvent,
hotkeyTriggered: HotkeyTriggeredEvent,
magictoolbarHide: MagicToolbarHideEvent,
magictoolbarShow: MagicToolbarShowEvent,
overlayDismiss: OverlayDismissEvent,
overlayNotify: OverlayNotifyEvent,
pickerAnchor: PickerAnchorEvent,
pickerClosing: PickerClosingEvent,
settingsChanged: SettingsChangedEvent
}>({
autodarkChanged: "autodark:changed",
displayState: "display:state",
displayTopology: "display:topology",
downloadUpdate: "download:update",
focusAnchor: "focus:anchor",
focusCursor: "focus:cursor",
focusState: "focus:state",
hotkeyTriggered: "hotkey:triggered",
magictoolbarHide: "magictoolbar:hide",
magictoolbarShow: "magictoolbar:show",
overlayDismiss: "overlay:dismiss",
overlayNotify: "overlay:notify",
pickerAnchor: "picker:anchor",
pickerClosing: "picker:closing",
settingsChanged: "settings:changed"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * One shadeable region in window-local physical px — a monitor's dimmable area,
 * already resolved to the work area (taskbar excluded) or the full monitor rect
 * (taskbar included) by the backend.
 */
export type AnchorRect = { left: number; top: number; right: number; bottom: number }
/**
 * The full persisted settings tree. Every field is `#[serde(default)]` so a
 * missing/partial persisted blob falls back per-field instead of failing the
 * whole parse (mirrors Zod `.catch` on the frontend).
 */
export type AppSettings = { appearance: AppearanceSettings; general: GeneralSettings; downloads: DownloadsSettings; hotkeys: HotkeysSettings; display: DisplaySettings; dayNight: DayNightSettings; rules: RulesSettings; focusRead: FocusReadSettings; focusBlur: FocusBlurSettings; magicx: MagicxSettings; autoDark: AutoDarkSettings }
/**
 * Appearance section — renderer-owned presentation knobs.
 */
export type AppearanceSettings = {
/**
 * BCP-47 locale tag the renderer's i18n layer loads ("en", "de", …).
 */
locale: string;
/**
 * Skip/shorten motion for users who prefer reduced motion.
 */
reducedMotion: boolean }
/**
 * `autodark:changed` — the Auto Dark scheduler applied new theme state; the
 * boolean is the resolved dark flag for the Windows system theme.
 */
export type AutoDarkChangedEvent = { systemDark: boolean }
/**
 * Auto Dark section (FEATURE-PARITY F9.5-F9.6) — schedule the Windows SYSTEM
 * theme, optionally driven by the day/night times, plus the taskbar
 * transparency effect. Owned by the auto-dark slice; the seam is
 * `crate::magicx::theme`.
 *
 * There is deliberately no app-theme field. DimRead's own UI is permanently
 * dark, and the removed `app_theme` wrote `AppsUseLightTheme` — i.e. it
 * re-themed every OTHER Windows app rather than this one.
 */
export type AutoDarkSettings = {
/**
 * Windows system-theme schedule: `light`|`dark`|`auto`|`disable`.
 */
systemTheme: string;
/**
 * Sunrise for the SYSTEM theme's `auto` (day→night) schedule, `"HH:MM"`.
 * Decoupled from the Display-tab blue-light schedule.
 */
systemSunrise: string;
/**
 * Sunset for the SYSTEM theme's `auto` schedule, `"HH:MM"`.
 */
systemSunset: string;
/**
 * Apply the transparent-taskbar effect (F9.6).
 */
taskbarTransparent: boolean }
/**
 * Day/night section — the sunrise/sunset schedule the display scheduler reads.
 */
export type DayNightSettings = { enabled: boolean;
/**
 * Derive sun times from `latitude`/`longitude` instead of the manual
 * `sunrise`/`sunset` strings.
 */
useLocation: boolean; latitude: number; longitude: number;
/**
 * Manual sunrise time, "HH:MM" (used when `use_location` is off).
 */
sunrise: string;
/**
 * Manual sunset time, "HH:MM".
 */
sunset: string;
/**
 * Width of the day↔night ramp window, in minutes.
 */
transitionMinutes: number }
/**
 * Which axis an edit targets.
 */
export type DisplayAxis = "brightness" | "kelvin"
/**
 * A single display-value edit: "set `axis` to `value` for `phase`, on
 * `monitor_id` (or every monitor when `None`)".
 */
export type DisplayEdit = { axis: DisplayAxis; phase: DisplayPhase;
/**
 * `None` = the active mode's preset (all monitors); `Some(id)` = that
 * monitor's override.
 */
monitorId: string | null; value: number }
/**
 * The engine's current output, surfaced to the UI badge, `display_current`, and
 * the `display:state` event. `brightness` is a percentage (0..=100).
 */
export type DisplayOutput = { kelvin: number; brightness: number; mode: string; phase: string;
/**
 * True only when Reading mode's compositor-wide grayscale matrix was
 * successfully installed. Other Reading-mode adjustments may still be
 * active when this is false.
 */
grayscaleApplied: boolean }
/**
 * Which day/night endpoint an edit lands on.
 */
export type DisplayPhase = "day" | "night"
/**
 * Display section — colour temperature / brightness / mode + per-monitor state.
 */
export type DisplaySettings = {
/**
 * Active mode id: `pause`|`health`|`game`|`movie`|`office`|`editing`|
 * `reading`|`custom`.
 */
mode: string;
/**
 * Widen the temperature range to 0..=10000 K (default 1000..=6500 K).
 */
wideRange: boolean;
/**
 * Extend the brightness range down to 0 % (default floor 10 %), letting the
 * screen dim to fully black (FEATURE-PARITY F2.2).
 */
brightnessWideRange: boolean;
/**
 * Suspend filtering while a full-screen app (e.g. a game) is foreground
 * (FEATURE-PARITY F1.11). On by default, like CareUEyes.
 */
disableOnFullscreen: boolean;
/**
 * Animate colour/brightness changes over ~400 ms.
 */
smoothTransition: boolean;
/**
 * Apply one value to every monitor; when off, use `monitor_overrides`.
 */
syncMonitors: boolean;
/**
 * Per-monitor overrides keyed by the display backend's durable monitor id.
 */
monitorOverrides: Partial<{ [key in string]: MonitorOverride }>;
/**
 * The eight editable preset modes keyed by mode id.
 */
modes: Partial<{ [key in string]: ModePreset }> }
/**
 * `display:state` — the display engine's current output (Kelvin / brightness% /
 * mode / phase), emitted on every applied change so the UI badge and any
 * per-window readout stay live without polling `display_current`.
 */
export type DisplayStateEvent = DisplayOutput
/**
 * `display:topology` — the set of displays changed after a native hot-plug,
 * disconnect, or display reconfiguration notification. Renderers subscribe to
 * this instead of periodically re-enumerating monitors.
 */
export type DisplayTopologyEvent = MonitorInfo[]
export type DownloadPhase = "queued" | "downloading" | "paused" | "completed" | "cancelled" | "failed"
/**
 * One download's renderer-facing state. Emitted as the `download:update`
 * payload on every phase change (plus throttled progress) and returned as a
 * list by `download_list`.
 */
export type DownloadSnapshot = {
/**
 * Caller-chosen stable id (also the registry key).
 */
id: string; url: string; fileName: string; phase: DownloadPhase;
/**
 * Canonical progress ratio in `[0, 1]`; `0` while the total is unknown.
 */
progress: number; downloadedBytes: number; totalBytes: number | null; speedBps: number | null; etaSeconds: number | null; error: string | null }
/**
 * `download:update` — one download's full snapshot, emitted on every state
 * change plus throttled (~10 Hz) progress while downloading.
 */
export type DownloadUpdateEvent = DownloadSnapshot
/**
 * Downloads section — download-manager tuning.
 */
export type DownloadsSettings = {
/**
 * Parallel download worker count, clamped to `1..=4`.
 */
concurrency: number }
/**
 * `focus:anchor` — the foreground-window rect + its monitor bounds (physical
 * px) while Focus Blur is active, so the renderer cuts a hole for the active
 * window in the tint. `taskbar` is true when the taskbar is included in the
 * dimmed area.
 *
 * `monitors` carries EVERY monitor's dimmable region (see [`AnchorRect`]), which
 * is what the whole-virtual-screen mode shades: the union of those rects rather
 * than the raw viewport. That is how `include_taskbar` is honoured with more
 * than one monitor (each region is the work area when the taskbar is excluded),
 * and it also leaves the gaps between non-contiguous monitors untinted.
 * `monitor_*` stays the ACTIVE window's monitor, used by `only_current_monitor`.
 *
 * `window_id` is the platform window handle (the `HWND` as a `u64` on Windows,
 * 0 where the platform has no durable handle). It exists so the renderer can
 * tell a MOVE of the focused window apart from a SWITCH to a different one: a
 * move must snap the cutout (springing after a dragged window reads as lag),
 * while a switch should glide. Handles comfortably fit a JS `number` — the
 * bindings export `u64` via `BigIntExportBehavior::Number`.
 */
export type FocusAnchorEvent = {
/**
 * Process-monotonic ordering for the renderer's subscribe-then-snapshot
 * handshake. The snapshot is applied only when it is newer than every live
 * event already observed by that renderer.
 */
sequence: number; windowId: number; x: number; y: number; width: number; height: number; monitorLeft: number; monitorTop: number; monitorRight: number; monitorBottom: number; taskbar: boolean; monitors: AnchorRect[] }
/**
 * Focus Blur section (FEATURE-PARITY F8.2) — dim/tint every background window
 * while the active window stays highlighted (Hazeover-style). Owned by the
 * focus-blur slice; the engine seam is `crate::focus::blur`.
 */
export type FocusBlurSettings = { enabled: boolean;
/**
 * Include the taskbar in the dimmed area.
 */
includeTaskbar: boolean;
/**
 * Only dim the monitor the active window is on.
 */
onlyCurrentMonitor: boolean;
/**
 * Animate the shade following the active window.
 */
animate: boolean;
/**
 * Shade opacity as a percentage (0..=100).
 */
transparency: number;
/**
 * Shade colour, `#rrggbb`.
 */
color: string }
/**
 * `focus:cursor` — the cursor position (physical px) while Focus Read is
 * active, so the renderer moves the clear band with the pointer.
 */
export type FocusCursorEvent = { x: number; y: number }
/**
 * Focus Read section (FEATURE-PARITY F8.1) — a horizontal clear band that
 * tracks the cursor while the rest of the screen is tinted/dimmed. Owned by
 * the focus-read slice; the engine seam is `crate::focus::read`.
 */
export type FocusReadSettings = {
/**
 * Shade opacity as a percentage (0..=100) — how strongly the area outside
 * the clear band is dimmed.
 */
transparency: number;
/**
 * Shade colour, `#rrggbb`.
 */
color: string;
/**
 * Height (px) of the transparent clear band that follows the cursor.
 */
height: number }
/**
 * Combined Focus activation state — the `focus_active_state` return value and
 * the `focus:state` event payload.
 */
export type FocusState = {
/**
 * Focus Read (clear band) is active.
 */
read: boolean;
/**
 * Focus Blur (background dim) is active.
 */
blur: boolean }
/**
 * `focus:state` — the combined Focus Read / Focus Blur activation, emitted on
 * every toggle so the `focus-overlay` renderer knows which tint mode to draw
 * (or to hide when both are off).
 */
export type FocusStateEvent = FocusState
/**
 * General section — desktop-shell behavior.
 */
export type GeneralSettings = {
/**
 * Launch the app at login (wired to tauri-plugin-autostart on save).
 */
autostart: boolean;
/**
 * Closing the app window hides to the tray instead of quitting.
 */
minimizeToTray: boolean }
/**
 * One live registration, as reported by `hotkey_list`.
 */
export type HotkeyInfo = { id: string; accelerator: string }
/**
 * `hotkey:triggered` — a registered global hotkey fired (key-down edge).
 * Built-in behaviors (e.g. `toggleMain`) run Rust-side BEFORE this broadcast;
 * renderers subscribe for app-level reactions (demos, toasts, custom ids).
 */
export type HotkeyTriggeredEvent = {
/**
 * The caller-chosen registration id (e.g. `"toggleMain"`).
 */
id: string;
/**
 * The accelerator the id is bound to (e.g. `"Ctrl+Shift+Space"`).
 */
accelerator: string }
/**
 * Hotkeys section — persisted global accelerators (Tauri accelerator strings
 * like `"Ctrl+Shift+Space"`). An empty string means "unbound". Registered at
 * startup and hot-swapped on every save (see `crate::hotkeys`).
 */
export type HotkeysSettings = {
/**
 * Toggles the APP window's visibility (show + focus / hide). "" disables
 * it. The field name predates the removal of the separate `main` window
 * and is kept because renaming it would orphan every persisted binding.
 */
toggleMain: string;
/**
 * Raise brightness one step. "" = unbound. (Effect wired by Agent D via
 * `crate::hotkeys::actions`.)
 */
brightnessUp: string;
/**
 * Lower brightness one step.
 */
brightnessDown: string;
/**
 * Warmer/cooler colour temperature one step (~55 K).
 */
tempUp: string;
/**
 * The opposite colour-temperature step.
 */
tempDown: string;
/**
 * Toggle the blue-light filter on/off.
 */
toggleFilter: string;
/**
 * Toggle Reading mode (full-screen grayscale).
 */
toggleReading: string;
/**
 * Toggle Editing mode (colour invert).
 */
toggleEditing: string;
/**
 * Toggle Focus Read (moving clear band, rest of screen dimmed). "" = unbound.
 * (Effect wired by the focus-read slice via `crate::focus`.)
 */
focusRead: string;
/**
 * Toggle Focus Blur (dim/tint all background windows). "" = unbound.
 */
focusBlur: string;
/**
 * Toggle Magic Window dark (per-window colour invert) on the current target.
 */
magicDark: string;
/**
 * Toggle Magic Window grayscale on the current target.
 */
magicGray: string }
/**
 * `magictoolbar:hide` — the Magic Toolbar left its target window; the renderer
 * plays its exit and Rust hides the `magic-toolbar` window.
 */
export type MagicToolbarHideEvent = Record<string, never>
/**
 * `magictoolbar:show` — position (physical px) the Magic Toolbar was shown at,
 * plus the current effect flags of its target window (so the toolbar highlights
 * the active Dark/Gray buttons).
 */
export type MagicToolbarShowEvent = { x: number; y: number; targetDark: boolean; targetGray: boolean }
/**
 * MagicX section (FEATURE-PARITY F9.1-F9.4, F9.7) — per-window dark/grayscale
 * effect plus the hover Magic Toolbar. Disabled by default. Owned by the
 * magic-toolbar slice; the engine seam is `crate::magicx`.
 */
export type MagicxSettings = {
/**
 * Master switch for the whole MagicX feature (default off, F9.7).
 */
enabled: boolean;
/**
 * Show the hover Magic Toolbar (Dark / Gray / Close) at the top of windows.
 */
toolbarEnabled: boolean;
/**
 * Toolbar accent colour, `#rrggbb`.
 */
toolbarColor: string;
/**
 * Toolbar horizontal alignment on the target window: `center`|`left`|`right`.
 */
toolbarAlign: string;
/**
 * Horizontal offset (px) applied to the aligned toolbar.
 */
toolbarOffset: number;
/**
 * Hover delay (ms) before the toolbar appears (0.3-0.5 s recommended).
 */
toolbarDelayMs: number }
/**
 * A single mode's colour-temperature + brightness endpoints. Day and night
 * values are interpolated by the display scheduler; `brightness_*` are
 * percentages (0..=100), `kelvin_*` are absolute Kelvin.
 */
export type ModePreset = { kelvinDay: number; kelvinNight: number; brightnessDay: number; brightnessNight: number }
/**
 * A physical monitor as seen by the display engine.
 *
 * `id` is a stable, backend-owned identifier — the key used everywhere else
 * (native gamma handles, per-monitor override maps, `display_preview`). It is
 * stable across a session and is what `display_list_monitors` returns to the
 * UI.
 */
export type MonitorInfo = {
/**
 * Native backend id, e.g. `\\.\DISPLAY1`, `macos:uuid:…`, or
 * `x11-output:edid-<hash>:DP-1`.
 */
id: string;
/**
 * 0-based enumeration index (paint order convenience for the UI strip).
 */
index: number;
/**
 * Human-readable monitor/adapter name for display in the UI.
 */
friendlyName: string;
/**
 * Whether this is the OS primary monitor.
 */
isPrimary: boolean }
/**
 * A per-monitor colour/brightness override (same shape as a [`ModePreset`],
 * applied when `display.sync_monitors` is off).
 */
export type MonitorOverride = { kelvinDay: number; kelvinNight: number; brightnessDay: number; brightnessNight: number }
/**
 * A top-level window as reported by [`rules_list_windows`], used by the rule
 * editor's window picker / Finder Tool.
 */
export type OpenWindow = {
/**
 * Stable per-window identity for this listing (the Win32 `HWND` as a
 * decimal string). Distinguishes two windows of the SAME process so the
 * picker can capture the exact title/class the user chose.
 */
id: string;
/**
 * Owning process image name (e.g. `photoshop.exe`).
 */
process: string;
/**
 * Window title bar text.
 */
title: string;
/**
 * Win32 window class name.
 */
className: string }
/**
 * `overlay:dismiss` — the overlay is being dismissed; the renderer plays its
 * exit animation and acknowledges its real completion to the backend.
 */
export type OverlayDismissEvent = { sequence: number }
/**
 * The resolved notification broadcast via `overlay:notify`: optional inputs
 * filled with their effective values (tone default, duration clamped).
 */
export type OverlayNotification = {
/**
 * Process-monotonic ordering for event/snapshot races.
 */
sequence: number; title?: string | null; message: string; tone: OverlayTone; durationMs: number }
/**
 * `overlay:notify` — show a notification in the overlay pill window. The
 * payload is the RESOLVED notification (tone/duration defaults filled in).
 */
export type OverlayNotifyEvent = OverlayNotification
/**
 * `overlay_notify` input: everything but the message is optional.
 */
export type OverlayNotifyPayload = { title?: string | null; message: string; tone?: OverlayTone | null; durationMs?: number | null }
/**
 * Authoritative lifecycle snapshot read only after event listeners are live.
 */
export type OverlaySnapshot = { sequence: number; notification?: OverlayNotification | null }
/**
 * Notification tone → the renderer maps it to status color tokens.
 */
export type OverlayTone = "neutral" | "success" | "warning" | "error"
/**
 * A section-granular patch: only the sections present are replaced (whole
 * section at a time, exactly like the renderer posts them).
 */
export type PartialSettings = { appearance?: AppearanceSettings | null; general?: GeneralSettings | null; downloads?: DownloadsSettings | null; hotkeys?: HotkeysSettings | null; display?: DisplaySettings | null; dayNight?: DayNightSettings | null; rules?: RulesSettings | null; focusRead?: FocusReadSettings | null; focusBlur?: FocusBlurSettings | null; magicx?: MagicxSettings | null; autoDark?: AutoDarkSettings | null }
/**
 * `picker:anchor` — the WINDOW-LOCAL rect of the visible picker panel inside
 * the full-work-area transparent backdrop window. The picker renderer stays
 * invisible until this lands, then draws the panel at the given rect.
 */
export type PickerAnchorEvent = { x: number; y: number; width: number; height: number }
/**
 * `picker:closing` — the close animation is starting; the renderer plays its
 * fade-out and acknowledges its actual completion (see `windows::placement`).
 */
export type PickerClosingEvent = Record<string, never>
/**
 * Latest panel rect for a race-free subscribe-then-snapshot handshake.
 */
export type PickerLifecycleSnapshot = { anchor?: PickerAnchorEvent | null; closing: boolean }
/**
 * One custom per-app rule: switch to `mode` while a matching window is active.
 */
export type Rule = { id: string;
/**
 * `process`|`class`|`title`.
 */
matchKind: string; pattern: string;
/**
 * Mode id to apply while the rule matches.
 */
mode: string }
/**
 * Rules section — the per-app auto-switch rules (engine owned by Agent C).
 */
export type RulesSettings = { enabled: boolean; items: Rule[] }
/**
 * `settings:changed` — broadcast to ALL windows after every durable settings
 * save so each renderer replaces its snapshot (and revision) with the
 * authoritative one.
 */
export type SettingsChangedEvent = { revision: number; settings: AppSettings }
/**
 * The authoritative settings snapshot: the tree plus the revision it was
 * read/written at.
 */
export type SettingsSnapshot = { revision: number; settings: AppSettings }

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE } from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __commandError__<E>(error: unknown): { status: "error"; error: E } {
	return { status: "error", error: error as E };
}

type __EventAccessor__<T> = __EventObj__<T> & {
	(handle: __WebviewWindow__): __EventObj__<T>;
};

type __EventMap__<T extends object> = {
	[K in keyof T]: __EventAccessor__<T[K]>;
};

function __makeWindowEventObj__<T>(
	name: string,
	window: __WebviewWindow__,
): __EventObj__<T> {
	return {
		listen: (cb) => window.listen<T>(name, cb),
		once: (cb) => window.once<T>(name, cb),
		emit: ((payload?: T) =>
			window.emit(name, payload)) as __EventObj__<T>["emit"],
	};
}

function __makeGlobalEventObj__<T>(name: string): __EventObj__<T> {
	return {
		listen: (cb) => TAURI_API_EVENT.listen<T>(name, cb),
		once: (cb) => TAURI_API_EVENT.once<T>(name, cb),
		emit: ((payload?: T) =>
			TAURI_API_EVENT.emit(name, payload)) as __EventObj__<T>["emit"],
	};
}

function __makeEventAccessor__<T>(name: string): __EventAccessor__<T> {
	const eventObj = __makeGlobalEventObj__<T>(name);
	const accessor = ((window: __WebviewWindow__) =>
		__makeWindowEventObj__<T>(name, window)) as __EventAccessor__<T>;
	accessor.listen = eventObj.listen;
	accessor.once = eventObj.once;
	accessor.emit = eventObj.emit;
	return accessor;
}

function __makeEvents__<T extends object>(
	mappings: Record<keyof T, string>,
): __EventMap__<T> {
	return new Proxy({} as __EventMap__<T>, {
		get: (_, event: string | symbol) =>
			__makeEventAccessor__<T[keyof T]>(mappings[event as keyof T]),
	});
}
